### ISSUE TITLE
Generating po tokens for direct YT stream links

### ISSUE THREAD

**Issue by TCH68k** [YunzheZJU/youtube-po-token-generator#11]
Just a question: after i got my po token, then how can i use it in the direct stream links of YT? If i got the JSOn with `poToken` and `visitorData` and i got this YT direct stream link:
```
https://rr1---sn-qpbpu8-c0qk.googlevideo.com/videoplayback?expire=1735200485&ei=hbpsZ5fxEcLGi9oP1rSkuAY&ip=IP.ADDRESS.WUZ.HERE&id=o-APJqVdvOz603FTCqiX6YwTHlPFWOIBvJeLOPZOrvqH7Q&itag=299&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&met=1735178885%2C&mh=jJ&mm=31%2C29&mn=sn-qpbpu8-c0qk%2Csn-c0q7lns7&ms=au%2Crdu&mv=m&mvi=1&pl=24&rms=au%2Cau&initcwndbps=3530000&bui=AfMhrI-rG4FAgM11LmNJ63RlHStWgghSZ_7xphTsVCE5UGU1FPjW5qWRePFCsC5ta7fgDGY4aoAsjCet&spc=x-caUPi2QD5CiXJ8d1exhPLCJgeInzRHU3xelAqz4rxemD_6V1yurvvwYkflpDM&vprv=1&svpuc=1&mime=video%2Fmp4&rqh=1&gir=yes&clen=1908177827&dur=3217.213&lmt=1701904508613687&mt=1735178462&fvip=4&keepalive=yes&fexp=51326932%2C51335594%2C51371294&c=ANDROID&txp=5432434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cbui%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRQIhAK4rKa1J2RiykQMcYxJZsNZmMBfzre639Hilzsf9DZr1AiADVyeNcl-4SIUWOeu4vfqJVjx7m-gR9NK7COslf7Q4fA%3D%3D&lsparams=met%2Cmh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Crms%2Cinitcwndbps&lsig=AGluJ3MwRAIgbr4Hr8O6IlDGhwLSCoDqfOpS_HxBPQOLF4RVnQCwnt0CIDXjFgZM-zM7-Zz0JekB6L5wm3l2CSOvui2pr3qwZkQd
```
What can i do with the token, to make this link work? I read somewhere, that the argument for the token is `pot`, but if i try to append `&pot=<token here>` to this link, i still got 403.

Any help is really appreciated.

**Comment by YunzheZJU** [comment]
I am sorry that perhaps this repo is not the right place to get your answer.

From my point of view, this link propably has nothing to do with poToken, likely an endpoint for video parts instead of an API where poToken usually taks effects. The combination of url params determines whether the server will return 403 or not. Usually this combination has limited lifetime and expires soon.

This material may gives you a description of when to use a poToken. https://github.com/LuanRT/BgUtils?tab=readme-ov-file#when-to-use-a-potoken

**Comment by TCH68k** [comment]
Thank you, it is still one step closer.

**Comment by TCH68k** [comment]
And it even does the link assembling: [https://github.com/LuanRT/BgUtils/issues/14](https://github.com/LuanRT/BgUtils/issues/14)

Thanks again for the suggestion.
